# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a02a2f98e64314db25de8f927e648098fe880ea42ca022a477215cd94fb08fff5b600aba3e14bab8be1dde8a7219c5d03dae21d1bdf4e8d37b1478864eb0989

test:
  secret_key_base: 7b6404a23042d1e73feafd2149f841a3ecd56de3905fc469e289d77839710de1037a5b39d29d5724d36917e3533374c3a798cad7582ff9045afea1e63897194e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
